# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3edf2765fea2b2a0708a90a496a66022ac2f251c1013108e62807e9e9c7b9101a814dbac2c40a94b93422470358cbc8ed72e23a727790609da39252d084b97b8

test:
  secret_key_base: fc28b5df8fc2befe4f56622f779b37a15ab310985622a8d57800073427a7998bbf67296471789884351c149ca4c16ee96462e156584f2a67a51b2665937cf35e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
